<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>EMI.NetUDPv2</RootNamespace>
    <AssemblyName>EMI.NetUDPv2</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>TRACE;DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EMI\EMI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>

</Project>
