<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>EMI</RootNamespace>
    <AssemblyName>EMI</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>TRACE;DEBUG;Debug</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartPackager\SmartPackager\SmartPackager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Indicators\Indicator.g.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Indicator.tt</DependentUpon>
    </Compile>
    <Compile Update="RPC\RPCFuncDelegate.g.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>RPCFuncDelegate.tt</DependentUpon>
    </Compile>
    <Compile Update="RPC\RPC.g.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>RPC.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Indicators\Indicator.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Indicator.g.cs</LastGenOutput>
    </None>
    <None Update="RPC\RPCFuncDelegate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>RPCFuncDelegate.g.cs</LastGenOutput>
    </None>
    <None Update="RPC\RPC.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>RPC.g.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>

</Project>
