<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>EMI.DebugServer</RootNamespace>
    <AssemblyName>EMI.DebugServer</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EMI\EMI.csproj">
      <SetConfiguration>Configuration=Debug</SetConfiguration>
    </ProjectReference>
  </ItemGroup>

</Project>