<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EMI.NetTCPV3\EMI.NetTCPV3.csproj" />
    <ProjectReference Include="..\EMI.NetStream\EMI.NetStream.csproj" />
    <ProjectReference Include="..\EMI\EMI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="server.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
