namespace EMI.DebugLog
{
    /// <summary>
    /// Сообщения для вывода в логи
    /// </summary>
    internal static class Messages
    {
        public static readonly LogMessage InitServer = LogMessage.Create(LogType.Message, "Server => init (service: {0})");
        public static readonly LogMessage ServerStarted = LogMessage.Create(LogType.Message, "Server => started");
        public static readonly LogMessage ServerStopped = LogMessage.Create(LogType.Message, "Server => stopped");
        public static readonly LogMessage ServerPingStarted = LogMessage.Create(LogType.Message, "Server => PingProcess => started");
        public static readonly LogMessage ServerPingStopped = LogMessage.Create(LogType.Message, "Server => PingProcess => stopped");

        public static readonly LogMessage InitClientSide = LogMessage.Create(LogType.Message, "Client => init on client side (service: {0})");
        public static readonly LogMessage InitServerSide = LogMessage.Create(LogType.Message, "Client => init on server side (service: {0})");
        public static readonly LogMessage ConnectBegin = LogMessage.Create(LogType.Message, "Client => connect begin (IsConnect = {0}; IsServerSide = {1})");
        public static readonly LogMessage ConnectStatus = LogMessage.Create(LogType.Message, "Client => INetworkClient.Connect() return status => {0}");

        public static readonly LogMessage ConnectCanceled = LogMessage.Create(LogType.Message, "Client => connection operation was canceled");
        public static readonly LogMessage ConnectDone = LogMessage.Create(LogType.Message, "Client => connect done!");
        public static readonly LogMessage ConnectUnsuccessful = LogMessage.Create(LogType.Message, "Client => connect unsuccessful!");
        public static readonly LogMessage ClientDisconnect = LogMessage.Create(LogType.Message, "Client => Client disconnect => message: {0}");
        public static readonly LogMessage AlreadyRunning = LogMessage.Create(LogType.CriticalError, "Client is already running!");

        public static readonly LogMessage PossibleReconnect = LogMessage.Create(LogType.CriticalError, "It is not possible to reconnect the client generated by the server!");
        public static readonly LogMessage AlreadyDisconnected = LogMessage.Create(LogType.Error, "Client => client is already disconnected!");
        public static readonly LogMessage LowDisconnectError = LogMessage.Create(LogType.CriticalError, "Client => LowDisconnect => error: {0}");
        public static readonly LogMessage DoCancellationError = LogMessage.Create(LogType.Error, "Client => DoCancellationRun => throw error: {0}");

        public static readonly LogMessage PingTimeout = LogMessage.Create(LogType.CriticalError, "Client => ProcessPing => timeout ({0} ms)");
        public static readonly LogMessage PingError = LogMessage.Create(LogType.CriticalError, "Client => ProcessPing => error: {0}");
        public static readonly LogMessage PingStopped = LogMessage.Create(LogType.Message, "Client => ProcessPing => stopped");
        public static readonly LogMessage AcceptPacketError = LogMessage.Create(LogType.CriticalError, "Client => ProcessAccept => packet accept => throw error: {0}");

        public static readonly LogMessage AcceptStopped = LogMessage.Create(LogType.Message, "Client => ProcessAccept => stopped");
        public static readonly LogMessage RPCReturnNotFound = LogMessage.Create(LogType.Warning, "Client => ProcessAccept => RPCReturn.TryGetValue => not found, timeout");
        public static readonly LogMessage BadPacketTypeForwarding = LogMessage.Create(LogType.CriticalError, "Client => ProcessAccept => bad packet type (forwarding not supported on clients)");
        public static readonly LogMessage NotFoundForwarding = LogMessage.Create(LogType.Error, "Client => EMI RC => not found forwarding!");

        public static readonly LogMessage BadPacketType = LogMessage.Create(LogType.Warning, "Client => ProcessAccept => bad packet type");
        public static readonly LogMessage RPCNotFound = LogMessage.Create(LogType.Warning, "Client => EMI RC => Not found method! [ID: {0}] ({1})");
        public static readonly LogMessage RPCRegisteredList = LogMessage.Create(LogType.Warning, "Client => EMI RC => Registered methods (global): [{0}]");
        public static readonly LogMessage RPCRegisteredListLocal = LogMessage.Create(LogType.Warning, "Client => EMI RC => Registered methods (local): [{0}]");
        public static readonly LogMessage RPCExecutionError = LogMessage.Create(LogType.Error, "Client => EMI RC => Exception in method [{0}]: {1}");
        public static readonly LogMessage AcceptStart = LogMessage.Create(LogType.Message, "Client => ProcessAccept => start");
        public static readonly LogMessage PingStart = LogMessage.Create(LogType.Message, "Client => ProcessPing => start");

        public static readonly LogMessage RateLimitSoftDrop = LogMessage.Create(LogType.Warning, "Client => RateLimit => soft drop (total drops: {0})");
        public static readonly LogMessage RateLimitKick = LogMessage.Create(LogType.CriticalError, "Client => RateLimit => hard limit exceeded, disconnecting (total drops: {0})");
    }
}
