<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>EMI.SyncInterface</RootNamespace>
    <AssemblyName>EMI.SyncInterface</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>TRACE;DEBUG;Debug</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartPackager\SmartPackager\SmartPackager.csproj" />
    <ProjectReference Include="..\EMI\EMI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Utils.g.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Utils.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Utils.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Utils.g.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>

</Project>