// <auto-generated>
// Этот файл сгенерирован T4 шаблоном Utils.Generated.tt
// Не редактируйте вручную — изменения будут потеряны при регенерации.
// </auto-generated>
using System;

namespace EMI.SyncInterface
{
    internal static partial class Utils
    {
        public static Delegate MakeRPCDelegate(Type[] types, object context, System.Reflection.MethodInfo mi)
        {
            switch (types.Length)
            {
                case 0: return Delegate.CreateDelegate(typeof(RPCfunc), context, mi);
                case 1: return Delegate.CreateDelegate(typeof(RPCfunc<>).MakeGenericType(types), context, mi);
                case 2: return Delegate.CreateDelegate(typeof(RPCfunc<,>).MakeGenericType(types), context, mi);
                case 3: return Delegate.CreateDelegate(typeof(RPCfunc<,,>).MakeGenericType(types), context, mi);
                case 4: return Delegate.CreateDelegate(typeof(RPCfunc<,,,>).MakeGenericType(types), context, mi);
                case 5: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,>).MakeGenericType(types), context, mi);
                case 6: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,>).MakeGenericType(types), context, mi);
                case 7: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,>).MakeGenericType(types), context, mi);
                case 8: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,>).MakeGenericType(types), context, mi);
                case 9: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,>).MakeGenericType(types), context, mi);
                case 10: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 11: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 12: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 13: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 14: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 15: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 16: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 17: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 18: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 19: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 20: return Delegate.CreateDelegate(typeof(RPCfunc<,,,,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                default: throw new IndexOutOfRangeException();
            }
        }

        public static Delegate MakeRPCDelegateOut(Type outType, Type[] inTypes, object context, System.Reflection.MethodInfo mi)
        {
            var types = new Type[inTypes.Length + 1];
            types[0] = outType;
            for (int i = 0; i < inTypes.Length; i++)
                types[i + 1] = inTypes[i];
            switch (types.Length)
            {
                case 1: return Delegate.CreateDelegate(typeof(RPCfuncOut<>).MakeGenericType(types), context, mi);
                case 2: return Delegate.CreateDelegate(typeof(RPCfuncOut<,>).MakeGenericType(types), context, mi);
                case 3: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,>).MakeGenericType(types), context, mi);
                case 4: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,>).MakeGenericType(types), context, mi);
                case 5: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,>).MakeGenericType(types), context, mi);
                case 6: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,>).MakeGenericType(types), context, mi);
                case 7: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,>).MakeGenericType(types), context, mi);
                case 8: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,>).MakeGenericType(types), context, mi);
                case 9: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,>).MakeGenericType(types), context, mi);
                case 10: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 11: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 12: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 13: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 14: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 15: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 16: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 17: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 18: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 19: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                case 20: return Delegate.CreateDelegate(typeof(RPCfuncOut<,,,,,,,,,,,,,,,,,,,>).MakeGenericType(types), context, mi);
                default: throw new IndexOutOfRangeException();
            }
        }

        private static Type GetRPCfuncDelegateType(Type[] types)
        {
            switch (types.Length)
            {
                case 0: return typeof(RPCfunc);
                case 1: return typeof(RPCfunc<>).MakeGenericType(types);
                case 2: return typeof(RPCfunc<,>).MakeGenericType(types);
                case 3: return typeof(RPCfunc<,,>).MakeGenericType(types);
                case 4: return typeof(RPCfunc<,,,>).MakeGenericType(types);
                case 5: return typeof(RPCfunc<,,,,>).MakeGenericType(types);
                case 6: return typeof(RPCfunc<,,,,,>).MakeGenericType(types);
                case 7: return typeof(RPCfunc<,,,,,,>).MakeGenericType(types);
                case 8: return typeof(RPCfunc<,,,,,,,>).MakeGenericType(types);
                case 9: return typeof(RPCfunc<,,,,,,,,>).MakeGenericType(types);
                case 10: return typeof(RPCfunc<,,,,,,,,,>).MakeGenericType(types);
                default: throw new IndexOutOfRangeException();
            }
        }

        private static Type GetRPCfuncOutDelegateType(Type[] types)
        {
            switch (types.Length)
            {
                case 1: return typeof(RPCfuncOut<>).MakeGenericType(types);
                case 2: return typeof(RPCfuncOut<,>).MakeGenericType(types);
                case 3: return typeof(RPCfuncOut<,,>).MakeGenericType(types);
                case 4: return typeof(RPCfuncOut<,,,>).MakeGenericType(types);
                case 5: return typeof(RPCfuncOut<,,,,>).MakeGenericType(types);
                case 6: return typeof(RPCfuncOut<,,,,,>).MakeGenericType(types);
                case 7: return typeof(RPCfuncOut<,,,,,,>).MakeGenericType(types);
                case 8: return typeof(RPCfuncOut<,,,,,,,>).MakeGenericType(types);
                case 9: return typeof(RPCfuncOut<,,,,,,,,>).MakeGenericType(types);
                case 10: return typeof(RPCfuncOut<,,,,,,,,,>).MakeGenericType(types);
                default: throw new IndexOutOfRangeException();
            }
        }
    }
}
